import type { Session } from './rota.types'
import { MOCK_SKILLS } from './mockSkills'

// Sessions mirror the DB schema. session_date/start_time/end_time are null = unscheduled.
// Scheduled sessions have a date within the Summer 2026 programme weeks.
export const MOCK_SESSIONS: Session[] = [
  // ── Unscheduled sessions (appear in the left panel) ─────────────────────
  {
    id: 'session-1',
    programme_id: 'prog-1',
    title: 'After School Youth Club',
    description: 'Supervised drop-in for S1–S4 pupils after school hours.',
    session_date: null,
    start_time: null,
    end_time: null,
    location: 'Clackmannan Community Centre',
    status: 'draft',
    min_staff: 2,
    max_staff: 4,
    session_type: 'drop-in',
    notes: null,
    required_skills: [MOCK_SKILLS[1], MOCK_SKILLS[2]], // Youth Work, Safeguarding
  },
  {
    id: 'session-2',
    programme_id: 'prog-1',
    title: 'Employability Workshop',
    description: 'CV writing and interview skills for young people aged 16–24.',
    session_date: null,
    start_time: null,
    end_time: null,
    location: 'Alloa Community Hub',
    status: 'draft',
    min_staff: 2,
    max_staff: 3,
    session_type: 'workshop',
    notes: null,
    required_skills: [MOCK_SKILLS[2], MOCK_SKILLS[3]], // Safeguarding, Employability Coaching
  },
  {
    id: 'session-3',
    programme_id: 'prog-1',
    title: 'Girls Evening Session',
    description: 'Safe social space for young women aged 13–19.',
    session_date: null,
    start_time: null,
    end_time: null,
    location: 'Tullibody Youth Centre',
    status: 'draft',
    min_staff: 2,
    max_staff: 3,
    session_type: 'social',
    notes: null,
    required_skills: [MOCK_SKILLS[1], MOCK_SKILLS[2]], // Youth Work, Safeguarding
  },
  {
    id: 'session-4',
    programme_id: 'prog-1',
    title: 'Football Coaching',
    description: 'Weekly coached football session for mixed group aged 12–18.',
    session_date: null,
    start_time: null,
    end_time: null,
    location: 'Sauchie Playing Fields',
    status: 'draft',
    min_staff: 2,
    max_staff: 4,
    session_type: 'sport',
    notes: null,
    required_skills: [MOCK_SKILLS[0], MOCK_SKILLS[4]], // First Aid, Sports Leadership
  },
  {
    id: 'session-5',
    programme_id: 'prog-1',
    title: 'Creative Arts Drop-In',
    description: 'Art, music and crafts open session for all young people.',
    session_date: null,
    start_time: null,
    end_time: null,
    location: 'Clackmannan Community Centre',
    status: 'draft',
    min_staff: 1,
    max_staff: 2,
    session_type: 'creative',
    notes: null,
    required_skills: [MOCK_SKILLS[1]], // Youth Work
  },
  // ── Pre-scheduled sessions (already on the week grid for demo) ────────────
  {
    id: 'session-6',
    programme_id: 'prog-1',
    title: 'Monday Drop-In',
    description: 'Weekly open drop-in session.',
    session_date: '2026-07-06',
    start_time: '13:00',
    end_time: '17:00',
    location: 'Clackmannan Community Centre',
    status: 'published',
    min_staff: 2,
    max_staff: 4,
    session_type: 'drop-in',
    notes: null,
    required_skills: [MOCK_SKILLS[1], MOCK_SKILLS[2]],
  },
  {
    id: 'session-7',
    programme_id: 'prog-1',
    title: 'Wednesday Sports',
    description: 'Outdoor sports and active play.',
    session_date: '2026-07-08',
    start_time: '14:00',
    end_time: '16:30',
    location: 'Sauchie Playing Fields',
    status: 'published',
    min_staff: 2,
    max_staff: 3,
    session_type: 'sport',
    notes: null,
    required_skills: [MOCK_SKILLS[0], MOCK_SKILLS[4]],
  },
]
